version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{checksum "src/package.json"}}
      - run:
          name: NPM Update
          command: cd src/ && npm i
      - save_cache:
          key: dep-cache-{{checksum "src/package.json"}}
          paths:
            - ./src/node_modules
      - run:
          name: download kakugen
          command: ./scripts/kakugen.sh
      - run:
          name: run test
          command: cd src/ && npm test

